"""empty message

Revision ID: 08bead29e35c
Revises: 
Create Date: 2023-07-20 11:32:32.524370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bead29e35c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_groups_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annual_income_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizenship_status_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_of_birth_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_release_cycle_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_level_adults_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_level_children_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marital_status_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_ethnic_origin_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('served_in_the_us_armed_forces_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('six_month_time_period_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total_number_of_people_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_table',
    sa.Column('respondent_sequence_number', sa.Integer(), nullable=False),
    sa.Column('data_release_cycle', sa.Integer(), nullable=True),
    sa.Column('six_month_time_period', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age_in_years_at_screening', sa.Integer(), nullable=True),
    sa.Column('race_ethnic_origin', sa.Integer(), nullable=True),
    sa.Column('served_in_the_us_armed_forces', sa.Integer(), nullable=True),
    sa.Column('country_of_birth', sa.Integer(), nullable=True),
    sa.Column('citizenship_status', sa.Integer(), nullable=True),
    sa.Column('education_level_children_youth_6_19', sa.Integer(), nullable=True),
    sa.Column('education_level_adults_20', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.Integer(), nullable=True),
    sa.Column('total_number_of_people_in_the_household', sa.Integer(), nullable=True),
    sa.Column('total_number_of_people_in_the_family', sa.Integer(), nullable=True),
    sa.Column('annual_household_income', sa.Integer(), nullable=True),
    sa.Column('annual_family_income', sa.Integer(), nullable=True),
    sa.Column('ratio_of_family_income_to_poverty', sa.Float(), nullable=True),
    sa.Column('hh_ref_person_gender', sa.Integer(), nullable=True),
    sa.Column('hh_ref_person_age', sa.Integer(), nullable=True),
    sa.Column('hh_ref_person_education_level', sa.Integer(), nullable=True),
    sa.Column('hh_ref_person_marital_status', sa.Integer(), nullable=True),
    sa.Column('hh_ref_person_spouse_education_level', sa.Integer(), nullable=True),
    sa.Column('full_sample_2_year_interview_weight', sa.Float(), nullable=True),
    sa.Column('full_sample_2_year_mec_exam_weight', sa.Float(), nullable=True),
    sa.Column('masked_variance_pseudo_psu', sa.Integer(), nullable=True),
    sa.Column('masked_variance_pseudo_stratum', sa.Integer(), nullable=True),
    sa.Column('money_spent_at_supermarket_grocery_store', sa.Float(), nullable=True),
    sa.Column('money_spent_on_nonfood_items', sa.Float(), nullable=True),
    sa.Column('money_spent_on_food_at_other_stores', sa.Float(), nullable=True),
    sa.Column('money_spent_on_eating_out', sa.Float(), nullable=True),
    sa.Column('money_spent_on_carryout_delivered_foods', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['age_in_years_at_screening'], ['age_groups_table.id'], ),
    sa.ForeignKeyConstraint(['annual_family_income'], ['annual_income_table.id'], ),
    sa.ForeignKeyConstraint(['annual_household_income'], ['annual_income_table.id'], ),
    sa.ForeignKeyConstraint(['citizenship_status'], ['citizenship_status_table.id'], ),
    sa.ForeignKeyConstraint(['country_of_birth'], ['country_of_birth_table.id'], ),
    sa.ForeignKeyConstraint(['data_release_cycle'], ['data_release_cycle_table.id'], ),
    sa.ForeignKeyConstraint(['education_level_adults_20'], ['education_level_adults_table.id'], ),
    sa.ForeignKeyConstraint(['education_level_children_youth_6_19'], ['education_level_children_table.id'], ),
    sa.ForeignKeyConstraint(['gender'], ['gender_table.id'], ),
    sa.ForeignKeyConstraint(['hh_ref_person_age'], ['age_groups_table.id'], ),
    sa.ForeignKeyConstraint(['hh_ref_person_education_level'], ['education_level_adults_table.id'], ),
    sa.ForeignKeyConstraint(['hh_ref_person_gender'], ['gender_table.id'], ),
    sa.ForeignKeyConstraint(['hh_ref_person_marital_status'], ['marital_status_table.id'], ),
    sa.ForeignKeyConstraint(['hh_ref_person_spouse_education_level'], ['education_level_adults_table.id'], ),
    sa.ForeignKeyConstraint(['marital_status'], ['marital_status_table.id'], ),
    sa.ForeignKeyConstraint(['race_ethnic_origin'], ['race_ethnic_origin_table.id'], ),
    sa.ForeignKeyConstraint(['served_in_the_us_armed_forces'], ['served_in_the_us_armed_forces_table.id'], ),
    sa.ForeignKeyConstraint(['six_month_time_period'], ['six_month_time_period_table.id'], ),
    sa.ForeignKeyConstraint(['total_number_of_people_in_the_family'], ['total_number_of_people_table.id'], ),
    sa.ForeignKeyConstraint(['total_number_of_people_in_the_household'], ['total_number_of_people_table.id'], ),
    sa.PrimaryKeyConstraint('respondent_sequence_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_table')
    op.drop_table('total_number_of_people_table')
    op.drop_table('six_month_time_period_table')
    op.drop_table('served_in_the_us_armed_forces_table')
    op.drop_table('race_ethnic_origin_table')
    op.drop_table('marital_status_table')
    op.drop_table('gender_table')
    op.drop_table('education_level_children_table')
    op.drop_table('education_level_adults_table')
    op.drop_table('data_release_cycle_table')
    op.drop_table('country_of_birth_table')
    op.drop_table('citizenship_status_table')
    op.drop_table('annual_income_table')
    op.drop_table('age_groups_table')
    # ### end Alembic commands ###
