"""empty message

Revision ID: 1d913ecf970a
Revises: ddf13ee78d29
Create Date: 2023-08-08 16:37:48.349670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d913ecf970a'
down_revision = 'ddf13ee78d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.create_foreign_key("foreign_key_123", 'ratio_of_family_income_to_poverty_table', ['ratio_of_family_income_to_poverty'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
