"""empty message

Revision ID: 327910dc53e4
Revises: 1d913ecf970a
Create Date: 2023-10-16 21:58:45.830714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327910dc53e4'
down_revision = '1d913ecf970a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.drop_column('money_spent_on_nonfood_items')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money_spent_on_nonfood_items', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
