"""empty message

Revision ID: ddf13ee78d29
Revises: 08bead29e35c
Create Date: 2023-08-08 16:27:08.208173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf13ee78d29'
down_revision = '08bead29e35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratio_of_family_income_to_poverty_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.alter_column('ratio_of_family_income_to_poverty',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_table', schema=None) as batch_op:
        batch_op.alter_column('ratio_of_family_income_to_poverty',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    op.drop_table('ratio_of_family_income_to_poverty_table')
    # ### end Alembic commands ###
